/**
 * Author:  Michael Wu
 * Created: May 14, 2022
 */

-- THE PURPOSE OF THIS SQL FILE IS JUST TO DEBUG AND CHECK THE DATABASE BECAUSE I DON'T REMEMBER ANYTHING FROM DB.FUND

SELECT * FROM IOTBAY.ORDERS;

SELECT * FROM IOTBAY.ORDERS WHERE ORDERID=1;

SELECT PRODUCTS, QUANTITY FROM IOTBAY.ORDERS WHERE ORDERID=1

SELECT PRODUCTS FROM IOTBAY.ORDERS WHERE ORDERID=1

SELECT QUANTITY FROM IOTBAY.ORDERS WHERE ORDERID=1